### ISSUE TITLE
Stopped working due to leading ./ on fd output

### ISSUE THREAD

**Issue by jchook** [jonhoo/proximity-sort#11]
Very happy user of this ever since I saw your Rust live coding.

It looks like `fd` recently [made a breaking change](https://github.com/sharkdp/fd/releases/tag/v8.3.0) to its output. Results now look more similar to `find` (with a leading `./`) due to a [vulnerability](https://github.com/sharkdp/fd/issues/760).

I fixed the issue by adding `--strip-cwd-prefix` to the `fd` call in my init.vim.

**Comment by jonhoo** [comment]
Good call! I pushed an update that should fix the problem. Please do report back if it doesn't!

**Comment by svenstaro** [comment]
@jonhoo please push a ~~release~~ tag with this in it.

**Comment by jonhoo** [comment]
@svenstaro It was released as 1.1.0, but I guess I forgot a git tag. I've pushed one now!
