### ISSUE TITLE
Could not install because could not find 'unix' in 'os'

### ISSUE THREAD

**Issue by MurraySobol** [jonhoo/proximity-sort#13]
Compiling indexmap v1.9.2
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\murra\.cargo\registry\src\github.com-1ecc6299db9ec823\c2rust-build-paths-0.17.0\src\lib.rs:35:26
   |
35 |             use std::os::unix::ffi::OsStrExt;
   |                          ^^^^ could not find `unix` in `os`

   Compiling proc-macro-error v1.0.4
error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
  --> C:\Users\murra\.cargo\registry\src\github.com-1ecc6299db9ec823\c2rust-build-paths-0.17.0\src\lib.rs:37:20
   |
37 |             OsStr::from_bytes(path)
   |                    ^^^^^^^^^^ function or associated item not found in `OsStr`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `c2rust-build-paths` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `c2rust v0.17.0`, intermediate artifacts can be found at `C:\Users\murra\AppData\Local\Temp\cargo-installNnT2jx`

**Comment by jonhoo** [comment]
Fixed in https://github.com/jonhoo/proximity-sort/commit/932f30375fb436a6ee68887daaed591a619c4a92, which has been released as 1.3.0 just now :tada:

**Comment by MurraySobol** [comment]
> Fixed in [932f303](https://github.com/jonhoo/proximity-sort/commit/932f30375fb436a6ee68887daaed591a619c4a92), which has been released as 1.3.0 just now 🎉

jonhoo: I'm missing something here, which module has been updated to 1.3.0??

**Comment by jonhoo** [comment]
This program itself — if you try installing it now it should pick up the new version and the install should work correctly.

**Comment by MurraySobol** [comment]
jonhoo: by "this program itself" which program do you mean??
I ran "cargo install proximity-sort" and it shows 1.3.0 installed and compiled.
I then ran "cargo install c2rsust" and got these errors (I think the same errors as before):
   Compiling c2rust-build-paths v0.17.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\murra\.cargo\registry\src\github.com-1ecc6299db9ec823\c2rust-build-paths-0.17.0\src\lib.rs:35:26
   |
35 |             use std::os::unix::ffi::OsStrExt;
   |                          ^^^^ could not find `unix` in `os`

   Compiling env_logger v0.10.0
   Compiling proc-macro-error v1.0.4
error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
  --> C:\Users\murra\.cargo\registry\src\github.com-1ecc6299db9ec823\c2rust-build-paths-0.17.0\src\lib.rs:37:20
   |
37 |             OsStr::from_bytes(path)
   |                    ^^^^^^^^^^ function or associated item not found in `OsStr`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `c2rust-build-paths` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `c2rust v0.17.0`, intermediate artifacts can be found at `C:\Users\murra\AppData\Local\Temp\cargo-installGvpbPp`

**Comment by jonhoo** [comment]
Oh, `c2rust` is a completely different library. It has nothing to do with this project. Previously, `proximity-sort` wouldn't build for Windows, but it does now. You'd have to file an issue with `c2rust` to have them fix that part :)
