### ISSUE TITLE
Publish lockfile

### ISSUE THREAD

**Issue by alecmev** [jonhoo/proximity-sort#3]
Please consider publishing `Cargo.lock`, otherwise it's impossible to do a `cargo build --locked` (handy for reproducible builds) on a tarball acquired from crates.io. [This is how](https://doc.rust-lang.org/1.28.0/cargo/reference/unstable.html#publish-lockfile).

Alternatively, if you're short on time or don't want to deal with nightly features, a git tag aligned with the version published on crates.io could suffice.

P.S. Published on AUR: [`proximity-sort`](https://aur.archlinux.org/packages/proximity-sort/)

**Comment by jonhoo** [comment]
As I understand it, this feature is now on by default: https://github.com/rust-lang/cargo/pull/7026. My guess is that it's just a matter of me not having issued a release since that were the case. I will issue a new release, and also tag all past releases!

**Comment by jonhoo** [comment]
Should hopefully be resolved with `1.0.5`.

**Comment by alecmev** [comment]
Can't believe the PR you linked doesn't come up on the first page of a [`publish-lockfile` search](https://github.com/rust-lang/cargo/search?q=publish-lockfile&type=Issues) :smile: 

Thanks! The lockfile is there.
