### ISSUE TITLE
Could not install because could not find 'unix' in 'os'

### ISSUE THREAD

**Issue by webmandman** [jonhoo/proximity-sort#7]
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Develoment\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\proximity-sort-1.0.6\src\main.rs:9:14
  |
9 | use std::os::unix::ffi::OsStrExt;
  |              ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `from_bytes` found for struct `std::ffi::OsStr` in the current scope
  --> C:\Develoment\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\proximity-sort-1.0.6\src\main.rs:78:42
   |
78 |         let proximity = Path::new(OsStr::from_bytes(&line))
   |                                          ^^^^^^^^^^ function or associated item not found in `std::ffi::OsStr`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
3  | use clap::osstringext::OsStrExt3;
   |

error[E0599]: no function or associated item named `from_bytes` found for struct `std::ffi::OsStr` in the current scope
   --> C:\Develoment\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\proximity-sort-1.0.6\src\main.rs:139:34
    |
139 |             .then_with(|| OsStr::from_bytes(&other.path).cmp(&OsStr::from_bytes(&self.path)))
    |                                  ^^^^^^^^^^ function or associated item not found in `std::ffi::OsStr`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
3   | use clap::osstringext::OsStrExt3;
    |

error[E0599]: no function or associated item named `from_bytes` found for struct `std::ffi::OsStr` in the current scope
   --> C:\Develoment\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\proximity-sort-1.0.6\src\main.rs:139:70
    |
139 |             .then_with(|| OsStr::from_bytes(&other.path).cmp(&OsStr::from_bytes(&self.path)))
    |                                                                      ^^^^^^^^^^ function or associated item not found in `std::ffi::OsStr`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
3   | use clap::osstringext::OsStrExt3;
    |

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: failed to compile `proximity-sort v1.0.6`, intermediate artifacts can be found at `C:\Users\DANIEL~1.MEJ\AppData\Local\Temp\cargo-installAdPjTt`

Caused by:
  could not compile `proximity-sort`.

To learn more, run the command again with --verbose.

**Comment by jonhoo** [comment]
Hello! Yes, `proximity-sort` does not currently work on Windows. If you want to submit a PR that fixes that, I'd be happy to review!
